id = "InuCoffee"
name = "Inu Coffee"
version = "0.0.2"
schema_version = 1
authors = ["Inuzdev, Carlos David Jorge"]
description = "A coffee theme by InuzDev - v1.1"
repository = "https://github.com/InuzDev/InuzDev-coffee"
